// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAnalysisPly = `-- name: ClaimAnalysisPly :one
WITH next AS MATERIALIZED (
    SELECT p.match_id, p.ply FROM analysis_plies p
    WHERE p.done_at IS NULL AND NOT p.dead
      AND (p.claimed_at IS NULL OR p.claimed_at < $1::timestamptz)
    ORDER BY p.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE analysis_plies t SET claimed_at = now()
FROM next n
WHERE t.match_id = n.match_id AND t.ply = n.ply
RETURNING t.match_id, t.ply, t.start_sfen, t.moves
`

type ClaimAnalysisPlyRow struct {
	MatchID   string
	Ply       int32
	StartSfen string
	Moves     []string
}

// 안 잰 手 하나를 집는다. 없으면 0행이다.
//
// 리스를 시각으로 받는다($1 = 지금 - 리스). 상수를 SQL 에 안 적는 것은 큐가 밴드를
// 안 적은 것과 같은 이유다 — 같은 값이 Go 와 SQL 에 두 벌 있으면 한쪽이 조용히 낡는다.
//
// 낡은 리스를 도로 집는 것이 이 문장의 두 번째 일이다. 워커가 배포나 스팟 회수로
// 사라지면 그 手는 claimed_at 만 찍힌 채 남고, 그 시각이 낡으면 여기가 되찾는다.
//
// 고르는 쪽을 MATERIALIZED CTE 로 못 박는다. `IN (SELECT ... LIMIT 1 FOR UPDATE)` 로 쓰면
// 계획에 따라 그 서브쿼리가 바깥 행마다 다시 돌아 여러 행을 잠그는데, 돌려받는 것은
// 한 행이라 나머지는 아무도 재지 않은 채 「집힌」 상태로 남는다. 워커 하나로 재 봤더니
// 그 값이 여덟까지 갔다(journal §115).
func (q *Queries) ClaimAnalysisPly(ctx context.Context, leaseBefore pgtype.Timestamptz) (ClaimAnalysisPlyRow, error) {
	row := q.db.QueryRow(ctx, claimAnalysisPly, leaseBefore)
	var i ClaimAnalysisPlyRow
	err := row.Scan(
		&i.MatchID,
		&i.Ply,
		&i.StartSfen,
		&i.Moves,
	)
	return i, err
}

const countAnalysisBacklog = `-- name: CountAnalysisBacklog :one
SELECT count(*) FROM analysis_plies
WHERE done_at IS NULL AND NOT dead
`

// 아직 안 잰 手数다. AnalysisBacklogPlies 가 이 값이고, 오토스케일의 신호가 된다.
//
// 그만둔 판은 안 센다. 아무도 재지 않을 것을 세면 백로그가 안 내려오고, 그 위에서
// 스케일 판단이 돈다.
func (q *Queries) CountAnalysisBacklog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalysisBacklog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMeasuredAnalysisPlies = `-- name: CountMeasuredAnalysisPlies :one
SELECT count(*) FROM analysis_plies
WHERE match_id = $1 AND done_at IS NOT NULL
`

// 그 판에서 미리 재 둔 手数다. 판이 끝날 때 남은 일의 크기를 이것으로 센다.
func (q *Queries) CountMeasuredAnalysisPlies(ctx context.Context, matchID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMeasuredAnalysisPlies, matchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const discardAnalysisMatch = `-- name: DiscardAnalysisMatch :exec
DELETE FROM analysis_plies WHERE match_id = $1
`

// 그 판의 행을 걷는다. 판이 끝난 뒤와, 반쪽이라 분석하지 않는 자리에서 부른다.
func (q *Queries) DiscardAnalysisMatch(ctx context.Context, matchID string) error {
	_, err := q.db.Exec(ctx, discardAnalysisMatch, matchID)
	return err
}

const enqueueAnalysisPly = `-- name: EnqueueAnalysisPly :exec

INSERT INTO analysis_plies (match_id, ply, start_sfen, moves)
SELECT $1::text,
       $2::int,
       $3::text,
       $4::text[]
WHERE NOT EXISTS (
    SELECT 1 FROM analysis_plies d
    WHERE d.match_id = $1::text AND d.dead
)
ON CONFLICT (match_id, ply) DO NOTHING
`

type EnqueueAnalysisPlyParams struct {
	MatchID   string
	Ply       int32
	StartSfen string
	Moves     []string
}

// 미리 재는 手의 줄(018). 메모리 채널이던 것을 표로 내렸고, 근거는 journal §115.
//
// 모든 잠금이 SKIP LOCKED 다 — 워커가 서로를 기다리는 자리를 만들지 않는다
// (LockQueueCandidates 와 같은 계열).
//
// 방금 둔 手를 줄에 세운다. 착수 경로가 이 문장을 기다리지 않는다 — 부르는 쪽이
// 배수구 goroutine 이다(matchAnalyzer.drain).
//
// 두 번 세워도 한 행이다(ON CONFLICT). 착수 경로가 같은 手를 두 번 부를 수 있고
// (matchRecords.counting 의 뒤따라온 자리) 같은 국면을 두 번 재는 것은 그대로 낭비다.
//
// 그만둔 판에는 안 쌓는다(NOT EXISTS). 안 걸면 그 판의 남은 手가 전부 행이 되어
// 밀린 양으로 세어지는데, 아무도 그것을 재지 않으므로 백로그가 안 내려온다.
func (q *Queries) EnqueueAnalysisPly(ctx context.Context, arg EnqueueAnalysisPlyParams) error {
	_, err := q.db.Exec(ctx, enqueueAnalysisPly,
		arg.MatchID,
		arg.Ply,
		arg.StartSfen,
		arg.Moves,
	)
	return err
}

const finishAnalysisPly = `-- name: FinishAnalysisPly :exec
UPDATE analysis_plies
SET done_at   = now(),
    before_cp = $2,
    after_cp  = $3,
    blunder   = $4,
    delta_win = $5,
    threshold = $6,
    decided   = $7
WHERE match_id = $1 AND ply = $8 AND done_at IS NULL
`

type FinishAnalysisPlyParams struct {
	MatchID   string
	BeforeCp  *int32
	AfterCp   *int32
	Blunder   *bool
	DeltaWin  *float64
	Threshold *float64
	Decided   *bool
	Ply       int32
}

// 잰 값을 그 행에 적는다.
//
// 행이 없으면 아무 일도 안 일어난다. 그것이 규약이다 — 판이 끝나 자리가 걷힌 뒤에
// 도착한 늦은 측정이 판을 되살리면 그 항목을 아무도 안 지운다(journal §106).
func (q *Queries) FinishAnalysisPly(ctx context.Context, arg FinishAnalysisPlyParams) error {
	_, err := q.db.Exec(ctx, finishAnalysisPly,
		arg.MatchID,
		arg.BeforeCp,
		arg.AfterCp,
		arg.Blunder,
		arg.DeltaWin,
		arg.Threshold,
		arg.Decided,
		arg.Ply,
	)
	return err
}

const giveUpAnalysisPlies = `-- name: GiveUpAnalysisPlies :exec
UPDATE analysis_plies SET dead = true
WHERE match_id = $1 AND done_at IS NULL
`

// 그 판을 미리 재는 것을 그만둔다. 아직 안 잰 행만 표시한다 — 이미 잰 값은 판이 끝날 때
// 그대로 쓰이고, 여기서 같이 덮으면 그만큼을 다시 재게 된다.
func (q *Queries) GiveUpAnalysisPlies(ctx context.Context, matchID string) error {
	_, err := q.db.Exec(ctx, giveUpAnalysisPlies, matchID)
	return err
}

const measuredAnalysisPlies = `-- name: MeasuredAnalysisPlies :many
SELECT ply, before_cp, after_cp, blunder, delta_win, threshold, decided
FROM analysis_plies
WHERE match_id = $1 AND done_at IS NOT NULL
ORDER BY ply
`

type MeasuredAnalysisPliesRow struct {
	Ply       int32
	BeforeCp  *int32
	AfterCp   *int32
	Blunder   *bool
	DeltaWin  *float64
	Threshold *float64
	Decided   *bool
}

// 그 판에서 미리 재 둔 것을 한 번에 읽는다.
//
// 手마다 묻지 않는다. 판이 끝나는 자리에서 手数만큼 왕복하면 그 자체가 밀리는 값이고,
// 이 표는 판 하나가 곧 한 묶음이라 한 번에 읽는 것이 자연스럽다.
func (q *Queries) MeasuredAnalysisPlies(ctx context.Context, matchID string) ([]MeasuredAnalysisPliesRow, error) {
	rows, err := q.db.Query(ctx, measuredAnalysisPlies, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeasuredAnalysisPliesRow
	for rows.Next() {
		var i MeasuredAnalysisPliesRow
		if err := rows.Scan(
			&i.Ply,
			&i.BeforeCp,
			&i.AfterCp,
			&i.Blunder,
			&i.DeltaWin,
			&i.Threshold,
			&i.Decided,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepAnalysisPlies = `-- name: SweepAnalysisPlies :exec
DELETE FROM analysis_plies WHERE created_at < $1
`

// 낡은 행을 걷는다. 판이 비정상으로 끝나면 DiscardAnalysisMatch 가 안 돌고, 그때
// 남는 행이 이 표의 유일한 누수다.
func (q *Queries) SweepAnalysisPlies(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, sweepAnalysisPlies, createdAt)
	return err
}
