// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkEnqueueAnalysisPlies implements pgx.CopyFromSource.
type iteratorForBulkEnqueueAnalysisPlies struct {
	rows                 []BulkEnqueueAnalysisPliesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkEnqueueAnalysisPlies) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkEnqueueAnalysisPlies) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MatchID,
		r.rows[0].Ply,
		r.rows[0].StartSfen,
		r.rows[0].Moves,
	}, nil
}

func (r iteratorForBulkEnqueueAnalysisPlies) Err() error {
	return nil
}

// 판 하나의 手를 한 번에 세운다. 취해 온 기보만 이 문장을 쓴다 — 대인전은 두는 동안 한
// 手씩 쌓지만(EnqueueAnalysisPly) 취해 온 판은 수순 전부를 이미 알고, 그래서 워커가 몇이든
// 手들이 병렬로 재어진다.
//
// ON CONFLICT 가 없다. 방금 만든 판의 번호라 (match_id, ply) 가 부딪힐 수가 없고,
// COPY 는 애초에 그 절을 못 든다.
func (q *Queries) BulkEnqueueAnalysisPlies(ctx context.Context, arg []BulkEnqueueAnalysisPliesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"analysis_plies"}, []string{"match_id", "ply", "start_sfen", "moves"}, &iteratorForBulkEnqueueAnalysisPlies{rows: arg})
}
