// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explore.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExploreSnapshot = `-- name: CreateExploreSnapshot :one

INSERT INTO explore_snapshots (user_id, name, handicap, moves)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateExploreSnapshotParams struct {
	UserID   int64
	Name     string
	Handicap string
	Moves    []string
}

type CreateExploreSnapshotRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// 검토 화면에서 저장한 국면(migrations/015). 판이 아니라 手合割 id 와 수순 한 줄이다.
//
// 개수를 안 막는다. 근거는 journal §96.
func (q *Queries) CreateExploreSnapshot(ctx context.Context, arg CreateExploreSnapshotParams) (CreateExploreSnapshotRow, error) {
	row := q.db.QueryRow(ctx, createExploreSnapshot,
		arg.UserID,
		arg.Name,
		arg.Handicap,
		arg.Moves,
	)
	var i CreateExploreSnapshotRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteExploreSnapshot = `-- name: DeleteExploreSnapshot :execrows
DELETE FROM explore_snapshots
WHERE id = $1
  AND user_id = $2
`

type DeleteExploreSnapshotParams struct {
	ID     int64
	UserID int64
}

// 위와 같은 이유로 주인을 조건에 둔다.
func (q *Queries) DeleteExploreSnapshot(ctx context.Context, arg DeleteExploreSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExploreSnapshot, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExploreSnapshots = `-- name: ListExploreSnapshots :many
SELECT id, name, handicap, moves, created_at
FROM explore_snapshots
WHERE user_id = $1
ORDER BY id DESC
`

type ListExploreSnapshotsRow struct {
	ID        int64
	Name      string
	Handicap  string
	Moves     []string
	CreatedAt pgtype.Timestamptz
}

// 주인을 = 로 받는다. 익명(user_id NULL)이 애초에 안 걸린다.
//
// LIMIT 이 없다. 개수 상한이 없으므로 여기서 자르면 지울 수 없는 행이 생긴다(journal §96).
func (q *Queries) ListExploreSnapshots(ctx context.Context, userID int64) ([]ListExploreSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listExploreSnapshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreSnapshotsRow
	for rows.Next() {
		var i ListExploreSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Handicap,
			&i.Moves,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameExploreSnapshot = `-- name: RenameExploreSnapshot :execrows
UPDATE explore_snapshots
SET name = $3
WHERE id = $1
  AND user_id = $2
`

type RenameExploreSnapshotParams struct {
	ID     int64
	UserID int64
	Name   string
}

// 주인이 아니면 0행이고, 부르는 쪽에서 그것이 404가 된다(GetGameForOwner 와 같은 규약).
func (q *Queries) RenameExploreSnapshot(ctx context.Context, arg RenameExploreSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameExploreSnapshot, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
