// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explain.sql

package db

import (
	"context"
)

const cachedExplanation = `-- name: CachedExplanation :one
UPDATE explain_cache
SET hits = hits + 1
WHERE key = $1
RETURNING body
`

// 키에 걸린 문장을 주면서 **히트를 센다.** 두 문장으로 나누면 세는 것을 빠뜨리기 쉽다.
// 없는 키면 아무 행도 안 돌아온다 — 부르는 쪽이 그것을 「miss」로 읽는다.
func (q *Queries) CachedExplanation(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, cachedExplanation, key)
	var body string
	err := row.Scan(&body)
	return body, err
}

const explainCacheStats = `-- name: ExplainCacheStats :one
SELECT count(*) AS entries, coalesce(sum(hits), 0)::bigint AS hits
FROM explain_cache
`

type ExplainCacheStatsRow struct {
	Entries int64
	Hits    int64
}

// 캐시가 실제로 듣고 있는지 보는 값이다. 발표 슬라이드의 히트율이 여기서 나온다.
func (q *Queries) ExplainCacheStats(ctx context.Context) (ExplainCacheStatsRow, error) {
	row := q.db.QueryRow(ctx, explainCacheStats)
	var i ExplainCacheStatsRow
	err := row.Scan(&i.Entries, &i.Hits)
	return i, err
}

const saveExplanation = `-- name: SaveExplanation :exec
INSERT INTO explain_cache (key, body, model)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO NOTHING
`

type SaveExplanationParams struct {
	Key   string
	Body  string
	Model *string
}

// 만든 문장을 남긴다. **같은 키가 있으면 덮지 않는다.**
//
// 먼저 만들어진 문장은 이미 화면에 나갔다. 같은 사실에 다른 문장이 나오기 시작하면
// 「같은 실수에는 같은 설명」이 깨지고, 문구를 고쳤을 때 무엇이 달라졌는지도 못 본다.
// 프롬프트를 고치는 쪽은 키를 바꾼다(explain.promptVersion).
func (q *Queries) SaveExplanation(ctx context.Context, arg SaveExplanationParams) error {
	_, err := q.db.Exec(ctx, saveExplanation, arg.Key, arg.Body, arg.Model)
	return err
}
