// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
)

const countGames = `-- name: CountGames :one
SELECT count(*) FROM games
`

func (q *Queries) CountGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInterventions = `-- name: CountInterventions :one
SELECT count(*) FROM interventions
`

func (q *Queries) CountInterventions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInterventions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (user_id, my_color, start_sfen)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateGameParams struct {
	UserID    *int64
	MyColor   string
	StartSfen *string
}

// 대국 기록. 기보와 개입을 남긴다.
//
// **개입으로 물러진 수가 여기서만 남는다.** 기보(game_moves)에는 확정된 수만 들어가므로,
// interventions 에 안 적으면 「개입이 막지 않았다면 실제로 뒀을 수」가 그대로 사라진다 —
// 개입에 오염되지 않은 유일한 실력 신호다 (docs/01-core.md §5).
//
// user_id 는 로그인 전이면 NULL이다 (002_anonymous_games.sql).
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGame, arg.UserID, arg.MyColor, arg.StartSfen)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const finishGame = `-- name: FinishGame :exec
UPDATE games SET finished_at = now(), result = $2 WHERE id = $1
`

type FinishGameParams struct {
	ID     int64
	Result *string
}

func (q *Queries) FinishGame(ctx context.Context, arg FinishGameParams) error {
	_, err := q.db.Exec(ctx, finishGame, arg.ID, arg.Result)
	return err
}

const insertIntervention = `-- name: InsertIntervention :exec
INSERT INTO interventions (game_id, ply, kind, category, delta_win, level_bucket, retracted_usi)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertInterventionParams struct {
	GameID       int64
	Ply          int32
	Kind         string
	Category     *string
	DeltaWin     *float64
	LevelBucket  *string
	RetractedUsi *string
}

// **같은 ply에 여러 행이 들어간다.** 한 국면에서 몇 수를 시도하고 전부 물러지는 일이
// 실제로 있고(docs/06-status.md §17), 그 반복 자체가 기록할 값이다. 그래서
// (game_id, ply) 는 유니크가 아니다.
func (q *Queries) InsertIntervention(ctx context.Context, arg InsertInterventionParams) error {
	_, err := q.db.Exec(ctx, insertIntervention,
		arg.GameID,
		arg.Ply,
		arg.Kind,
		arg.Category,
		arg.DeltaWin,
		arg.LevelBucket,
		arg.RetractedUsi,
	)
	return err
}

const insertMove = `-- name: InsertMove :exec
INSERT INTO game_moves (game_id, ply, usi, eval_cp)
VALUES ($1, $2, $3, $4)
ON CONFLICT (game_id, ply) DO UPDATE
SET usi = EXCLUDED.usi, eval_cp = EXCLUDED.eval_cp
`

type InsertMoveParams struct {
	GameID int64
	Ply    int32
	USI    string
	EvalCp *int32
}

// **확정된 수만 들어온다.** 물러진 수가 여기 들어가면 기보가 롤백을 반영하지 못한다.
//
// 같은 ply를 다시 쓰는 것은 롤백 뒤 다시 둔 경우다. 덮어쓴다 — 기보는 「지금 판에
// 남아 있는 수순」이지 시도의 목록이 아니다. 시도는 interventions 가 센다.
func (q *Queries) InsertMove(ctx context.Context, arg InsertMoveParams) error {
	_, err := q.db.Exec(ctx, insertMove,
		arg.GameID,
		arg.Ply,
		arg.USI,
		arg.EvalCp,
	)
	return err
}
