// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGameStyleTag = `-- name: AddGameStyleTag :exec

UPDATE games
SET style_tags = array_append(style_tags, $1::text)
WHERE id = $2 AND NOT (style_tags @> ARRAY[$1::text])
`

type AddGameStyleTagParams struct {
	Code   string
	GameID int64
}

// ─── 전법·囲い ───────────────────────────────────────────────
// 사람이 그 판에서 실제로 짠 이름. 근거는 009_game_style_tags.sql.
//
// 같은 이름을 두 번 안 담는다. 囲い는 판에서 매번 다시 세어지므로(game.styleTags) 한 판에
// 같은 코드가 수십 번 온다 — 세션이 본 것을 기억해 거르지만, 이어하는 판은 그 기억을 잃는다
// (세션이 연결에 매여 있다, §51). 그래서 거르는 자리를 여기에도 둔다.
func (q *Queries) AddGameStyleTag(ctx context.Context, arg AddGameStyleTagParams) error {
	_, err := q.db.Exec(ctx, addGameStyleTag, arg.Code, arg.GameID)
	return err
}

const claimGameForResume = `-- name: ClaimGameForResume :one
UPDATE games
SET result = NULL, finished_at = NULL
WHERE id = $1
  AND user_id = $2
  AND result = 'abandoned'
  -- 위 질의와 같은 조건이 여기에도 있어야 한다. 목록에서만 빼면 /ws/game?resume=<id>
  -- 로 번호를 직접 넣어 그대로 열린다 — 되짚기의 목록과 상세가 같은 조건을 갖는 것과
  -- 같은 자리다(GetGameForOwner).
  AND match_id IS NULL
RETURNING id, my_color, start_sfen, opening_tag
`

type ClaimGameForResumeParams struct {
	ID     int64
	UserID *int64
}

type ClaimGameForResumeRow struct {
	ID         int64
	MyColor    string
	StartSfen  *string
	OpeningTag *string
}

// 점유와 되열기가 한 문장이다. result = 'abandoned' 를 조건에 두었으므로 두 번째
// 요청은 0행을 받는다 — 탭 두 개가 같은 판을 동시에 이어하려 할 때 뒤엣것이 여기서
// 걸리고, 그래야 세션 goroutine 둘이 한 대국 행에 기록을 겹쳐 쓰지 않는다.
//
// finished_at 도 같이 지운다. 안 지우면 「끝난 시각이 있는데 두는 중인 판」이 남는다.
func (q *Queries) ClaimGameForResume(ctx context.Context, arg ClaimGameForResumeParams) (ClaimGameForResumeRow, error) {
	row := q.db.QueryRow(ctx, claimGameForResume, arg.ID, arg.UserID)
	var i ClaimGameForResumeRow
	err := row.Scan(
		&i.ID,
		&i.MyColor,
		&i.StartSfen,
		&i.OpeningTag,
	)
	return i, err
}

const countGameHintStages = `-- name: CountGameHintStages :many
SELECT sfen_key, max(stage)::int AS stage
FROM game_hints
WHERE game_id = $1
GROUP BY sfen_key
`

type CountGameHintStagesRow struct {
	SFENKey string
	Stage   int32
}

// 국면마다 몇 단계까지 열렸나. 이어하는 판이 이것으로 「이 국면은 이미 답을 봤다」를
// 되찾는다 — 세션의 기억은 연결과 함께 사라진다(§51).
func (q *Queries) CountGameHintStages(ctx context.Context, gameID int64) ([]CountGameHintStagesRow, error) {
	rows, err := q.db.Query(ctx, countGameHintStages, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGameHintStagesRow
	for rows.Next() {
		var i CountGameHintStagesRow
		if err := rows.Scan(&i.SFENKey, &i.Stage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGameHints = `-- name: CountGameHints :one
SELECT count(*) FROM game_hints WHERE game_id = $1
`

// 이어하는 판이 6회 제한을 리셋하지 않게 한다(game.Config.HintsUsed) — CountGameUndos
// 와 같은 자리, 같은 이유다.
func (q *Queries) CountGameHints(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGameHints, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGameResultsForOwner = `-- name: CountGameResultsForOwner :many
SELECT g.result, count(*) AS games
FROM games g
WHERE EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
  AND g.result IN ('win', 'loss', 'draw')
  AND g.user_id IS NOT DISTINCT FROM $1::bigint
  -- 대인전 판은 안 센다(match_id IS NULL). 개입이 없는 판이라 분모에만 들어가고,
  -- 그러면 「崩れやすいところ」의 비율이 그만큼 희석된다(journal §83).
  AND g.match_id IS NULL
GROUP BY g.result
`

type CountGameResultsForOwnerRow struct {
	Result *string
	Games  int64
}

// 마이페이지의 전적. 결과가 나온 판만 세는 것은 ListGamesForOwner 와 같은 규칙이다 —
// 목록에 안 보이는 판이 전적에는 들어가면 두 화면이 같은 사람에 대해 다른 수를 말한다.
//
// 한 수도 안 둔 판을 빼는 것도 같은 이유다(그쪽의 EXISTS).
func (q *Queries) CountGameResultsForOwner(ctx context.Context, ownerID *int64) ([]CountGameResultsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, countGameResultsForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGameResultsForOwnerRow
	for rows.Next() {
		var i CountGameResultsForOwnerRow
		if err := rows.Scan(&i.Result, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGameStyleTagsForOwner = `-- name: CountGameStyleTagsForOwner :many
SELECT t.code::text AS code, count(*) AS games
FROM games g
CROSS JOIN LATERAL unnest(g.style_tags) AS t(code)
WHERE EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
  AND g.result IN ('win', 'loss', 'draw')
  AND g.user_id IS NOT DISTINCT FROM $1::bigint
  -- 대인전 판은 안 센다(match_id IS NULL). 개입이 없는 판이라 분모에만 들어가고,
  -- 그러면 「崩れやすいところ」의 비율이 그만큼 희석된다(journal §83).
  AND g.match_id IS NULL
GROUP BY t.code
`

type CountGameStyleTagsForOwnerRow struct {
	Code  string
	Games int64
}

// 마이페이지의 「짠 진형」. 판 수를 센다 — 한 판에서 같은 이름이 여러 번 나오는 일은
// 위 질의가 이미 막았으므로, 이 숫자는 언제나 「그 이름으로 둔 판이 몇 판인가」다.
//
// 거르는 조건이 전적·약점과 같아야 한다: 셋이 한 화면에 서는데 모집단이 갈리면
// 「12판 뒀는데 진형은 30판에서 나온 것」이 된다.
// ::text 를 적어야 한다. unnest 의 결과 타입을 sqlc 가 못 읽어 interface{} 로
// 만들고, 그러면 코드가 문자열인지 아닌지를 부르는 쪽이 매번 확인해야 한다.
func (q *Queries) CountGameStyleTagsForOwner(ctx context.Context, ownerID *int64) ([]CountGameStyleTagsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, countGameStyleTagsForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountGameStyleTagsForOwnerRow
	for rows.Next() {
		var i CountGameStyleTagsForOwnerRow
		if err := rows.Scan(&i.Code, &i.Games); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGameUndos = `-- name: CountGameUndos :one
SELECT count(*) FROM game_undos WHERE game_id = $1
`

// 이어하는 판이 3회 제한을 리셋하지 않게 한다(game.Config.UndoUsed). 세션은 연결에
// 매여 있어 이어할 때마다 새로 서는데, 카운터도 같이 0이 되면 제한이 제한이 아니다.
func (q *Queries) CountGameUndos(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGameUndos, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGames = `-- name: CountGames :one
SELECT count(*) FROM games
`

func (q *Queries) CountGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImportsSince = `-- name: CountImportsSince :one
SELECT count(*) FROM games
WHERE user_id = $1 AND imported_from IS NOT NULL AND started_at >= $2
`

type CountImportsSinceParams struct {
	UserID    *int64
	StartedAt pgtype.Timestamptz
}

// 그 사람이 언제부터 지금까지 취해 온 판 수. 하루 몫의 벽이 이 값으로 선다.
//
// 판당 手数만큼의 탐색이라(server/kifu_import.go) 이 벽이 곧 엔진 예산의 벽이다.
func (q *Queries) CountImportsSince(ctx context.Context, arg CountImportsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportsSince, arg.UserID, arg.StartedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInterventionCategoriesForOwner = `-- name: CountInterventionCategoriesForOwner :many
SELECT i.category, count(*) AS hits
FROM interventions i
JOIN games g ON g.id = i.game_id
WHERE EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
  AND g.result IN ('win', 'loss', 'draw')
  AND g.user_id IS NOT DISTINCT FROM $1::bigint
  -- 대인전 판은 안 센다(match_id IS NULL). 개입이 없는 판이라 분모에만 들어가고,
  -- 그러면 「崩れやすいところ」의 비율이 그만큼 희석된다(journal §83).
  AND g.match_id IS NULL
GROUP BY i.category
`

type CountInterventionCategoriesForOwnerRow struct {
	Category *string
	Hits     int64
}

// 마이페이지의 약점. 판을 가로질러 센다 — 총평은 한 판 안에서 세지만(server/summary.go)
// 「무엇이 약한가」는 한 판으로 답할 것이 아니다.
//
// 거르는 조건이 위와 같아야 한다: 전적에 안 들어간 판의 개입이 약점에는 들어가면
// 같은 화면의 두 숫자가 다른 모집단을 센다.
func (q *Queries) CountInterventionCategoriesForOwner(ctx context.Context, ownerID *int64) ([]CountInterventionCategoriesForOwnerRow, error) {
	rows, err := q.db.Query(ctx, countInterventionCategoriesForOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountInterventionCategoriesForOwnerRow
	for rows.Next() {
		var i CountInterventionCategoriesForOwnerRow
		if err := rows.Scan(&i.Category, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInterventions = `-- name: CountInterventions :one
SELECT count(*) FROM interventions
`

func (q *Queries) CountInterventions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInterventions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one

INSERT INTO games (user_id, my_color, start_sfen, opening_tag)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateGameParams struct {
	UserID     *int64
	MyColor    string
	StartSfen  *string
	OpeningTag *string
}

// 대국 기록. 기보와 개입을 남긴다.
//
// 개입으로 물러진 수가 여기서만 남는다. 기보(game_moves)에는 확정된 수만 들어가므로,
// interventions 에 안 적으면 그 수가 그대로 사라진다(docs/01-core.md §5).
//
// user_id 는 로그인 전이면 NULL이다 (002_anonymous_games.sql).
//
// opening_tag 는 사람이 고른 상대의 진형 id다 (internal/book). 「おまかせ」면 NULL.
// 이 칸이 있어야 이어하기가 상대를 원래대로 다시 세운다 — 북은 상태를 안 들고 매번
// (start_sfen, moves) 에서 다시 구하므로(game.bookOpponent) id 하나면 그 자리로 돌아간다.
func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.UserID,
		arg.MyColor,
		arg.StartSfen,
		arg.OpeningTag,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createImportedGame = `-- name: CreateImportedGame :one
INSERT INTO games (user_id, my_color, start_sfen, imported_from)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateImportedGameParams struct {
	UserID       *int64
	MyColor      string
	StartSfen    *string
	ImportedFrom *string
}

// 밖에서 둔 판을 취해 온 자리. 자리가 하나다 — 상대의 몫은 안 만든다.
//
// opening_tag 가 없다. 그 칸은 「사람이 고른 컴퓨터의 진형」이라 채울 것이 없다
// (CreateMatchGame 과 같은 이유).
//
// user_id 가 NULL 로 오지 않는다. 로그인한 사람만 취해 올 수 있다 — 익명끼리는 구별할
// 수단이 없어서(002_anonymous_games.sql) 「누구의 기보인가」에 답할 수가 없다.
func (q *Queries) CreateImportedGame(ctx context.Context, arg CreateImportedGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, createImportedGame,
		arg.UserID,
		arg.MyColor,
		arg.StartSfen,
		arg.ImportedFrom,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMatchGame = `-- name: CreateMatchGame :one
INSERT INTO games (user_id, my_color, start_sfen, match_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateMatchGameParams struct {
	UserID    *int64
	MyColor   string
	StartSfen *string
	MatchID   *string
}

// 대인전 한 판의 한쪽 몫이다. 같은 대국이 이 질의로 두 번 불려 행 두 개가 된다 —
// 그래야 소유 검사를 타는 다섯 질의가 한 줄도 안 바뀐다(012_match_games.sql).
//
// opening_tag 가 없다. 그 칸은 「사람이 고른 컴퓨터의 진형」이라 상대가 사람이면
// 채울 것이 없고, 빈 값을 넣으면 이어하기가 없는 북을 찾는다.
//
// user_id 가 NULL 로 오지 않는다. 대인전은 로그인한 사람만이라(internal/match 의 Room)
// 익명 판이 여기로 올 수 없다 — 컬럼 자체는 그대로 nullable 이다(002).
func (q *Queries) CreateMatchGame(ctx context.Context, arg CreateMatchGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMatchGame,
		arg.UserID,
		arg.MyColor,
		arg.StartSfen,
		arg.MatchID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const declineResume = `-- name: DeclineResume :execrows
UPDATE games
SET result = 'declined'
WHERE id = $1
  AND user_id = $2
  AND result = 'abandoned'
  -- 이어하기 세 질의가 같은 조건을 갖는다. 대인전 행은 이 장치가 닿을 자리가 아니다 —
  -- 지금은 두 상태 다 어느 목록에도 안 뜨므로 눈에 보이는 차이가 없지만, 셋 중 하나만
  -- 빠져 있으면 나중에 상태의 뜻이 바뀌는 날 그 하나가 구멍이 된다.
  AND match_id IS NULL
`

type DeclineResumeParams struct {
	ID     int64
	UserID *int64
}

// 「いいえ」다. 행을 지우지 않는다 — 그 판의 개입과 기보가 실력 추정의 원본이고
// (docs/01-core.md §5), 사람이 안 이어하겠다고 한 것과 기록을 버리는 것은 다른 일이다.
//
// declined 는 abandoned 의 하위 상태다: 중단된 채로 끝났고 사람이 그러기로 정했다.
// 갈라 두는 이유는 하나뿐이다 — 이걸 다시 물어보지 않기 위해서다.
func (q *Queries) DeclineResume(ctx context.Context, arg DeclineResumeParams) (int64, error) {
	result, err := q.db.Exec(ctx, declineResume, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMovesFrom = `-- name: DeleteMovesFrom :exec
DELETE FROM game_moves WHERE game_id = $1 AND ply >= $2
`

type DeleteMovesFromParams struct {
	GameID int64
	Ply    int32
}

// 무르기가 지우는 것은 사람의 수와 그 뒤 상대의 응수까지다. 手数로 자른다 — 개수로
// 세면 기보에 구멍이 있을 때 엉뚱한 수가 남는다(review.detailOf 의 같은 판단).
func (q *Queries) DeleteMovesFrom(ctx context.Context, arg DeleteMovesFromParams) error {
	_, err := q.db.Exec(ctx, deleteMovesFrom, arg.GameID, arg.Ply)
	return err
}

const finishGame = `-- name: FinishGame :exec
UPDATE games SET finished_at = now(), result = $2 WHERE id = $1
`

type FinishGameParams struct {
	ID     int64
	Result *string
}

func (q *Queries) FinishGame(ctx context.Context, arg FinishGameParams) error {
	_, err := q.db.Exec(ctx, finishGame, arg.ID, arg.Result)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, my_color, started_at, finished_at, result, start_sfen, opening_tag, match_id, imported_from
FROM games
WHERE id = $1
`

type GetGameRow struct {
	ID           int64
	MyColor      string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Result       *string
	StartSfen    *string
	OpeningTag   *string
	MatchID      *string
	ImportedFrom *string
}

// 여기서는 개입을 세지 않는다. 어차피 아래에서 전부 읽어 오므로, 따로 센 숫자와
// 실제로 온 줄 수가 두는 중인 판에서 어긋날 수 있다 — 목록(ListGames)은 줄을 안 읽으니
// 거기서만 센다.
func (q *Queries) GetGame(ctx context.Context, id int64) (GetGameRow, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.MyColor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Result,
		&i.StartSfen,
		&i.OpeningTag,
		&i.MatchID,
		&i.ImportedFrom,
	)
	return i, err
}

const getGameForOwner = `-- name: GetGameForOwner :one
SELECT id, my_color, started_at, finished_at, result, start_sfen, opening_tag, match_id, imported_from
FROM games
WHERE id = $1
  AND result IN ('win', 'loss', 'draw')
  AND user_id IS NOT DISTINCT FROM $2::bigint
`

type GetGameForOwnerParams struct {
	ID      int64
	OwnerID *int64
}

type GetGameForOwnerRow struct {
	ID           int64
	MyColor      string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Result       *string
	StartSfen    *string
	OpeningTag   *string
	MatchID      *string
	ImportedFrom *string
}

// 주인이 아니면 0행이다. 부르는 쪽에서 그것이 404가 된다 — 403이면 「그 번호의
// 판이 있다」를 알려주는 셈이라, 남의 판 개수를 세어 볼 수 있다.
//
// 끝나지 않은 판도 0행이다 — ListGamesForOwner 와 같은 조건이고, 같은 이유로 404다.
// 「있지만 못 본다」를 알려주는 순간 중단된 판의 존재가 새어 나간다.
func (q *Queries) GetGameForOwner(ctx context.Context, arg GetGameForOwnerParams) (GetGameForOwnerRow, error) {
	row := q.db.QueryRow(ctx, getGameForOwner, arg.ID, arg.OwnerID)
	var i GetGameForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.MyColor,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Result,
		&i.StartSfen,
		&i.OpeningTag,
		&i.MatchID,
		&i.ImportedFrom,
	)
	return i, err
}

const insertHint = `-- name: InsertHint :exec

INSERT INTO game_hints (game_id, ply, sfen_key, stage, best_usi)
VALUES ($1, $2, $3, $4, $5)
`

type InsertHintParams struct {
	GameID  int64
	Ply     int32
	SFENKey string
	Stage   int32
	BestUsi string
}

// ─── 부른 힌트 ───────────────────────────────────────────────
// 사람이 불러서 받은 최선수 힌트. 개입과 갈라 두는 이유는 010_game_hints.sql.
func (q *Queries) InsertHint(ctx context.Context, arg InsertHintParams) error {
	_, err := q.db.Exec(ctx, insertHint,
		arg.GameID,
		arg.Ply,
		arg.SFENKey,
		arg.Stage,
		arg.BestUsi,
	)
	return err
}

const insertIntervention = `-- name: InsertIntervention :exec
INSERT INTO interventions (
    game_id, ply, kind, category, delta_win, level_bucket, retracted_usi,
    best_cp, after_cp
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertInterventionParams struct {
	GameID       int64
	Ply          int32
	Kind         string
	Category     *string
	DeltaWin     *float64
	LevelBucket  *string
	RetractedUsi *string
	BestCp       *int32
	AfterCp      *int32
}

// (game_id, ply) 는 유니크가 아니다. 한 국면에서 몇 수를 시도하고 전부 물러지는 일이
// 실제로 있고 그 반복이 곧 기록할 값이다(journal §17).
// 칸별 규약은 store.Intervention 에 있다.
func (q *Queries) InsertIntervention(ctx context.Context, arg InsertInterventionParams) error {
	_, err := q.db.Exec(ctx, insertIntervention,
		arg.GameID,
		arg.Ply,
		arg.Kind,
		arg.Category,
		arg.DeltaWin,
		arg.LevelBucket,
		arg.RetractedUsi,
		arg.BestCp,
		arg.AfterCp,
	)
	return err
}

const insertMove = `-- name: InsertMove :exec
INSERT INTO game_moves (game_id, ply, usi, eval_cp)
VALUES ($1, $2, $3, $4)
ON CONFLICT (game_id, ply) DO UPDATE
SET usi = EXCLUDED.usi, eval_cp = EXCLUDED.eval_cp
`

type InsertMoveParams struct {
	GameID int64
	Ply    int32
	USI    string
	EvalCp *int32
}

// 확정된 수만 들어온다. 물러진 수가 여기 들어가면 기보가 롤백을 반영하지 못한다.
//
// 같은 ply를 다시 쓰는 것은 롤백 뒤 다시 둔 경우다. 덮어쓴다 — 기보는 「지금 판에
// 남아 있는 수순」이지 시도의 목록이 아니다. 시도는 interventions 가 센다.
func (q *Queries) InsertMove(ctx context.Context, arg InsertMoveParams) error {
	_, err := q.db.Exec(ctx, insertMove,
		arg.GameID,
		arg.Ply,
		arg.USI,
		arg.EvalCp,
	)
	return err
}

const insertUndo = `-- name: InsertUndo :exec

INSERT INTO game_undos (game_id, ply, usi, eval_cp)
VALUES ($1, $2, $3, (SELECT eval_cp FROM game_moves WHERE game_id = $1 AND ply = $2))
`

type InsertUndoParams struct {
	GameID int64
	Ply    int32
	USI    string
}

// ─── 무르기 ─────────────────────────────────────────────────
// 사람이 스스로 무른 수. 개입과 갈라 두는 이유는 008_game_undos.sql.
//
// 평가치는 인자로 안 받는다. 그 값은 판정이 game_moves 에 이미 채워 뒀거나 아직
// 안 채웠거나 둘 중 하나이고, 세션이 그것을 다시 들고 다니면 같은 숫자가 두 벌이 된다.
// 여기서 옮겨 담고 아래 DeleteMovesFrom 이 원본을 지운다 — 순서가 뒤집히면 NULL이 남는다.
func (q *Queries) InsertUndo(ctx context.Context, arg InsertUndoParams) error {
	_, err := q.db.Exec(ctx, insertUndo, arg.GameID, arg.Ply, arg.USI)
	return err
}

const listGameInterventions = `-- name: ListGameInterventions :many
SELECT ply, kind, category, delta_win, level_bucket, retracted_usi, best_cp, after_cp
FROM interventions
WHERE game_id = $1
ORDER BY ply, id
`

type ListGameInterventionsRow struct {
	Ply          int32
	Kind         string
	Category     *string
	DeltaWin     *float64
	LevelBucket  *string
	RetractedUsi *string
	BestCp       *int32
	AfterCp      *int32
}

// 같은 ply에 여러 행이 온다(InsertIntervention). id 로 이어 정렬해 물러진 순서를
// 지킨다 — 한 국면에서 두 번 걸렸을 때 어느 쪽이 먼저였는지가 곧 이야기다.
func (q *Queries) ListGameInterventions(ctx context.Context, gameID int64) ([]ListGameInterventionsRow, error) {
	rows, err := q.db.Query(ctx, listGameInterventions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameInterventionsRow
	for rows.Next() {
		var i ListGameInterventionsRow
		if err := rows.Scan(
			&i.Ply,
			&i.Kind,
			&i.Category,
			&i.DeltaWin,
			&i.LevelBucket,
			&i.RetractedUsi,
			&i.BestCp,
			&i.AfterCp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameMoves = `-- name: ListGameMoves :many
SELECT ply, usi, eval_cp FROM game_moves WHERE game_id = $1 ORDER BY ply
`

type ListGameMovesRow struct {
	Ply    int32
	USI    string
	EvalCp *int32
}

// eval_cp 는 先手 관점이고 NULL일 수 있다(store.RecordedMove).
func (q *Queries) ListGameMoves(ctx context.Context, gameID int64) ([]ListGameMovesRow, error) {
	rows, err := q.db.Query(ctx, listGameMoves, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameMovesRow
	for rows.Next() {
		var i ListGameMovesRow
		if err := rows.Scan(&i.Ply, &i.USI, &i.EvalCp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameUndos = `-- name: ListGameUndos :many
SELECT ply, usi, eval_cp FROM game_undos WHERE game_id = $1 ORDER BY ply, id
`

type ListGameUndosRow struct {
	Ply    int32
	USI    string
	EvalCp *int32
}

// 같은 ply에 여러 행이 온다(무르고 다시 두고 또 무른 경우). id 로 이어 정렬해 무른
// 순서를 지킨다 — ListGameInterventions 와 같은 규약이다.
func (q *Queries) ListGameUndos(ctx context.Context, gameID int64) ([]ListGameUndosRow, error) {
	rows, err := q.db.Query(ctx, listGameUndos, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameUndosRow
	for rows.Next() {
		var i ListGameUndosRow
		if err := rows.Scan(&i.Ply, &i.USI, &i.EvalCp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many

SELECT
    g.id,
    g.my_color,
    g.started_at,
    g.finished_at,
    g.result,
    (SELECT count(*) FROM game_moves m WHERE m.game_id = g.id) AS move_count,
    (SELECT count(*) FROM interventions i WHERE i.game_id = g.id) AS intervention_count,
    g.match_id,
    -- 재채점이 취해 온 판을 빼야 한다. 그 판에는 개입 루프가 안 돌아서 임계치를 넘은
    -- 수가 기보에 그대로 남아 있고, 섞으면 「통과한 수는 임계치 아래」가 깨진다
    -- (calibrate_measure_test.go).
    g.imported_from,
    -- 재채점이 手合割을 알아야 한다(internal/handicap). 기준점이 판마다 다르면 낙폭을
    -- 판을 가로질러 비교할 수 없고, 그 비교가 이 질의를 쓰는 유일한 이유다(journal §39).
    g.start_sfen
FROM games g
WHERE EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
ORDER BY g.id DESC
LIMIT $1
`

type ListGamesRow struct {
	ID                int64
	MyColor           string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	Result            *string
	MoveCount         int64
	InterventionCount int64
	MatchID           *string
	ImportedFrom      *string
	StartSfen         *string
}

// ─── 리뷰(읽기) ─────────────────────────────────────────────
//
// 리뷰 화면의 첫 목록. 최신부터.
//
// 한 수도 안 둔 판은 빼고 센다. 연결만 열렸다 끊긴 판이 실제로 그렇게 남는데
// (ws 핸들러가 붙는 즉시 CreateGame 한다), 되짚을 것이 없는 줄을 목록 맨 위에 놓으면
// 진짜 대국이 아래로 밀린다. 세는 쪽과 거르는 쪽이 같은 EXISTS 라 둘이 어긋나지 않는다.
//
// 정렬은 id 하나로 한다. started_at 은 now() 라 같은 초에 여러 판이 들어가면 순서가
// 흔들리는데, id 는 시퀀스라 그 자리에서 갈린다.
func (q *Queries) ListGames(ctx context.Context, limit int32) ([]ListGamesRow, error) {
	rows, err := q.db.Query(ctx, listGames, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesRow
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.MyColor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Result,
			&i.MoveCount,
			&i.InterventionCount,
			&i.MatchID,
			&i.ImportedFrom,
			&i.StartSfen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForOwner = `-- name: ListGamesForOwner :many
SELECT
    g.id,
    g.my_color,
    g.started_at,
    g.finished_at,
    g.result,
    (SELECT count(*) FROM game_moves m WHERE m.game_id = g.id) AS move_count,
    (SELECT count(*) FROM interventions i WHERE i.game_id = g.id) AS intervention_count,
    -- 대인전 판은 여기 그대로 뜬다. 마이페이지의 집계에서만 빠진다(journal §83) —
    -- 그쪽은 개입 비율이 뜻을 갖는 자리이고, 목록은 「무엇을 뒀나」라 뜻이 다르다.
    g.match_id,
    -- 취해 온 판인가. 값이 아니라 있는가만 밖으로 나간다(020_imported_games.sql).
    g.imported_from,
    -- 手合割을 되짚는 유일한 칸이다(internal/handicap 의 Of). 칸을 새로 만들지 않은
    -- 이유가 이것이다 — 시작 국면이 곧 手合이라, 이름을 따로 적으면 둘이 갈릴 수 있다.
    g.start_sfen
FROM games g
WHERE EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
  AND g.result IN ('win', 'loss', 'draw')
  AND g.user_id IS NOT DISTINCT FROM $2::bigint
ORDER BY g.id DESC
LIMIT $1
`

type ListGamesForOwnerParams struct {
	Limit   int32
	OwnerID *int64
}

type ListGamesForOwnerRow struct {
	ID                int64
	MyColor           string
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	Result            *string
	MoveCount         int64
	InterventionCount int64
	MatchID           *string
	ImportedFrom      *string
	StartSfen         *string
}

// 화면이 쓰는 쪽이다. 위 ListGames 는 주인을 안 보므로 측정 전용이다.
//
// 주인이 NULL(로그인 안 함)이면 익명 판만 보인다. 익명 판은 서로 구별할 수단이
// 애초에 없으므로 지금까지와 같고, 갈리는 것은 로그인한 판이 그 사람에게만
// 보인다는 쪽이다 (docs/02-architecture.md §7 위협 2).
//
// 결과가 나온 판만 준다 (journal §51). 두는 중(result NULL)도, 중단된
// 판(abandoned·declined)도 안 나간다 — 되짚을 것이 없는 줄이고, 중단된 판은 이어하기가
// 가져갈 몫이다. 아래 GetGameForOwner 와 같은 조건이어야 한다: 목록에서만 빼면
// /reviews/<id> 주소로 그냥 열린다(§46).
func (q *Queries) ListGamesForOwner(ctx context.Context, arg ListGamesForOwnerParams) ([]ListGamesForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listGamesForOwner, arg.Limit, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesForOwnerRow
	for rows.Next() {
		var i ListGamesForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.MyColor,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Result,
			&i.MoveCount,
			&i.InterventionCount,
			&i.MatchID,
			&i.ImportedFrom,
			&i.StartSfen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHintTaken = `-- name: MarkHintTaken :exec
UPDATE game_hints
SET taken = $1
WHERE game_id = $2 AND sfen_key = $3
`

type MarkHintTakenParams struct {
	Taken   *bool
	GameID  int64
	SFENKey string
}

// 알려준 수를 실제로 뒀는가. 그 국면의 줄 전부에 적는다 — 단계가 둘이면 행이 둘인데,
// 사람이 답을 본 것은 한 번이라 둘이 같은 답을 가져야 한다.
func (q *Queries) MarkHintTaken(ctx context.Context, arg MarkHintTakenParams) error {
	_, err := q.db.Exec(ctx, markHintTaken, arg.Taken, arg.GameID, arg.SFENKey)
	return err
}

const resumableGameForOwner = `-- name: ResumableGameForOwner :one

SELECT
    g.id,
    g.my_color,
    g.started_at,
    g.opening_tag,
    -- 이어하기 카드가 手合을 말하는 자리다. 위 ListGamesForOwner 와 같은 이유로 이름이
    -- 아니라 국면을 든다.
    g.start_sfen,
    (SELECT count(*) FROM game_moves m WHERE m.game_id = g.id) AS move_count
FROM games g
WHERE g.user_id = $1
  AND g.result = 'abandoned'
  AND EXISTS (SELECT 1 FROM game_moves m WHERE m.game_id = g.id)
  -- 대인전 판은 이어할 수 없다(journal §83). 이어하기는 엔진 대국의 장치라, 여기에
  -- 대인전 판이 걸리면 사람과 두던 수순이 엔진 세션으로 이어진다 — 그 판의 두 행이
  -- 그 자리에서 갈라져(한쪽만 자라고 다른 쪽은 abandoned 로 남는다) 같은 대국이 아니게 된다.
  --
  -- 배포가 대국 중에 끼면 실제로 그 상태가 만들어진다: 테이블이 접히면서(abort) 수가
  -- 있는 행이 abandoned 로 닫히고, 그것이 정확히 이 질의의 조건이다.
  AND g.match_id IS NULL
  -- 취해 온 판도 이어할 수 없다. 지금은 걸릴 수가 없다 — 그 판은 win·loss·draw 로만
  -- 닫히고(server 의 importedResultOf) abandoned 가 되는 경로가 없다. 조건을 적어 두는
  -- 것은 그 사실이 다른 파일에 있기 때문이다: 실패한 취해 오기를 abandoned 로 닫는
  -- 코드가 들어오는 날, 이 질의가 남이 딴 데서 둔 수순을 엔진 세션으로 이어 준다.
  AND g.imported_from IS NULL
ORDER BY g.id DESC
LIMIT 1
`

type ResumableGameForOwnerRow struct {
	ID         int64
	MyColor    string
	StartedAt  pgtype.Timestamptz
	OpeningTag *string
	StartSfen  *string
	MoveCount  int64
}

// ─── 이어하기 ───────────────────────────────────────────────
// 근거와 정한 것 셋은 journal §46 · §51.
//
// 로그인한 사람만이다. 셋 다 주인을 = 로 받아 익명 판(user_id NULL)이 애초에
// 안 걸린다 — 익명끼리는 구별할 수단이 없어서(002_anonymous_games.sql) 「누구의 중단된
// 판인가」에 답할 수가 없다.
//
// 이어할 수 있는 판 하나. 가장 최근 것 하나만 준다 — 목록을 주면 사람이 「어느 판을
// 이어할까」를 고르는 화면이 되는데, 물음은 「두던 판을 이어할까」 하나다.
//
// 한 수도 안 둔 판은 뺀다(ListGames 와 같은 EXISTS). 연결만 열렸다 끊긴 판이 그렇게
// 남는데, 그것을 이어하는 것은 새 판을 여는 것과 같다.
func (q *Queries) ResumableGameForOwner(ctx context.Context, userID *int64) (ResumableGameForOwnerRow, error) {
	row := q.db.QueryRow(ctx, resumableGameForOwner, userID)
	var i ResumableGameForOwnerRow
	err := row.Scan(
		&i.ID,
		&i.MyColor,
		&i.StartedAt,
		&i.OpeningTag,
		&i.StartSfen,
		&i.MoveCount,
	)
	return i, err
}

const setMoveEval = `-- name: SetMoveEval :exec
UPDATE game_moves SET eval_cp = $3 WHERE game_id = $1 AND ply = $2
`

type SetMoveEvalParams struct {
	GameID int64
	Ply    int32
	EvalCp *int32
}

// 평가치만 채운다. 수를 덮지 않는다 — upsert로 두면 물러진 수로 기보를 덮는 길이 생긴다.
// 없는 ply면 아무 일도 안 한다(평가치가 수보다 먼저 오는 경로가 없다).
func (q *Queries) SetMoveEval(ctx context.Context, arg SetMoveEvalParams) error {
	_, err := q.db.Exec(ctx, setMoveEval, arg.GameID, arg.Ply, arg.EvalCp)
	return err
}
