// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kb.sql

package db

import (
	"context"
)

const knowledgeForTags = `-- name: KnowledgeForTags :many
SELECT title, body
FROM kb_chunks
WHERE tags && $1::text[]
  AND verified_by IS NOT NULL
`

type KnowledgeForTagsRow struct {
	Title string
	Body  string
}

// 태그로 kb_chunks를 찾는다. GIN 인덱스가 잡는다(001_init.sql).
// verified_by IS NOT NULL 조건은 부분 인덱스와 같은 절이다 — 검증 안 된 행은 안 나온다.
func (q *Queries) KnowledgeForTags(ctx context.Context, tags []string) ([]KnowledgeForTagsRow, error) {
	rows, err := q.db.Query(ctx, knowledgeForTags, tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeForTagsRow
	for rows.Next() {
		var i KnowledgeForTagsRow
		if err := rows.Scan(&i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
