// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Edge struct {
	ParentKey   string
	USI         string
	ChildKey    *string
	Tags        []string
	EvalByDepth []int32
}

type ExplainCache struct {
	Key       string
	Body      string
	Model     *string
	Hits      int32
	CreatedAt pgtype.Timestamptz
}

type Game struct {
	ID         int64
	UserID     *int64
	MyColor    string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Result     *string
	OpeningTag *string
	RootKey    *string
	StartSfen  *string
}

type GameMove struct {
	GameID  int64
	Ply     int32
	USI     string
	SFENKey *string
	EvalCp  *int32
}

type Intervention struct {
	ID           int64
	GameID       int64
	Ply          int32
	Kind         string
	Category     *string
	DeltaWin     *float64
	LevelBucket  *string
	RetractedUsi *string
	HintedTag    *string
	Taken        *bool
	ExplainTier  *int16
	CostYen      pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
}

type KbChunk struct {
	ID            int64
	Title         string
	Body          string
	Tags          []string
	SourceUrl     string
	SourceLicense string
	VerifiedBy    *string
	Embedding     *pgvector.Vector
	CreatedAt     pgtype.Timestamptz
}

type Position struct {
	SFENKey       string
	SideToMove    string
	PlyHint       *int32
	Candidates    []byte
	ComputedDepth int32
	CreatedAt     pgtype.Timestamptz
}

type SkillProfile struct {
	UserID    int64
	RatingEst float64
	RatingSd  float64
	Weakness  []byte
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID          int64
	Provider    string
	ProviderUid string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}
