// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Edge struct {
	ParentKey   string
	USI         string
	ChildKey    *string
	Tags        []string
	EvalByDepth []int32
}

type Game struct {
	ID         int64
	UserID     *int64
	MyColor    string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Result     *string
	OpeningTag *string
	RootKey    *string
	StartSfen  *string
	StyleTags  []string
	MatchID    *string
}

type GameHint struct {
	ID        int64
	GameID    int64
	Ply       int32
	SFENKey   string
	Stage     int32
	BestUsi   string
	Taken     *bool
	CreatedAt pgtype.Timestamptz
}

type GameMove struct {
	GameID  int64
	Ply     int32
	USI     string
	SFENKey *string
	EvalCp  *int32
}

type GameQuiz struct {
	GameID      int64
	Version     int32
	Payload     []byte
	GeneratedAt pgtype.Timestamptz
}

type GameUndo struct {
	ID        int64
	GameID    int64
	Ply       int32
	USI       string
	EvalCp    *int32
	CreatedAt pgtype.Timestamptz
}

type Intervention struct {
	ID           int64
	GameID       int64
	Ply          int32
	Kind         string
	Category     *string
	DeltaWin     *float64
	LevelBucket  *string
	RetractedUsi *string
	HintedTag    *string
	Taken        *bool
	CreatedAt    pgtype.Timestamptz
	// 판정 당시 최선수의 cp(수번 측 관점). 제지형만. 과거 행은 NULL
	BestCp *int32
	// 물러진 수를 둔 뒤의 cp(수번 측 관점). 제지형만. 과거 행은 NULL
	AfterCp *int32
}

type Position struct {
	SFENKey       string
	SideToMove    string
	PlyHint       *int32
	Candidates    []byte
	ComputedDepth int32
	CreatedAt     pgtype.Timestamptz
}

type SkillProfile struct {
	UserID          int64
	RatingEst       float64
	RatingSd        float64
	Weakness        []byte
	UpdatedAt       pgtype.Timestamptz
	SkillLoss       *float64
	SkillSamples    int32
	RatingGames     int32
	RatingUpdatedAt pgtype.Timestamptz
}

type User struct {
	ID          int64
	Provider    string
	ProviderUid string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}
