// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countQueueWaiting = `-- name: CountQueueWaiting :one
SELECT count(*) FROM match_queue WHERE room_id IS NULL AND seen_at >= $1
`

// 지금 대기열에 서 있는 사람 수다. 화면에 나가지 않는다 — 운영 확인과 테스트용이다.
func (q *Queries) CountQueueWaiting(ctx context.Context, seenAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countQueueWaiting, seenAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const joinQueue = `-- name: JoinQueue :one

INSERT INTO match_queue (user_id, rating, deviation)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET seen_at = now()
RETURNING user_id, rating, deviation, joined_at
`

type JoinQueueParams struct {
	UserID    int64
	Rating    float64
	Deviation float64
}

type JoinQueueRow struct {
	UserID    int64
	Rating    float64
	Deviation float64
	JoinedAt  pgtype.Timestamptz
}

// 대인전 대기열. 근거는 journal §92 · §98.
//
// 밴드 식이 여기 없다. 이 파일이 하는 일은 잠그고 오래된 순으로 주는 것까지이고,
// 고르는 것은 internal/queue 가 한다 — 식을 여기 적으면 같은 식이 두 벌이 된다.
//
// 소유자 조건이 늘 있다. 여기 오는 user_id 는 언제나 서명 쿠키에서 나온 값이다(server/auth.go).
//
// 대기열에 서거나, 이미 서 있으면 살아 있다고 알린다. 한 사람이 한 행이라 멱등이다.
//
// 두 번째 호출이 레이팅을 다시 안 쓴다. 서 있는 동안 그 값이 바뀔 수가 없고(대기 중에
// 판이 끝나지 않는다), 다시 쓰면 joined_at 을 지키는 의미가 없어진다 — 밴드가 그 값으로
// 넓어지므로 매 재시도마다 처음으로 돌아간다.
//
// 짝이 이미 잡힌 행도 seen_at 만 갱신하고 그대로 둔다. 그 행은 주인이 읽고 지운다 —
// 부르는 쪽이 이 문장 앞에서 그것을 먼저 본다(TakeQueueSeat).
func (q *Queries) JoinQueue(ctx context.Context, arg JoinQueueParams) (JoinQueueRow, error) {
	row := q.db.QueryRow(ctx, joinQueue, arg.UserID, arg.Rating, arg.Deviation)
	var i JoinQueueRow
	err := row.Scan(
		&i.UserID,
		&i.Rating,
		&i.Deviation,
		&i.JoinedAt,
	)
	return i, err
}

const leaveQueue = `-- name: LeaveQueue :exec
DELETE FROM match_queue WHERE user_id = $1
`

// 대기열에서 빠진다. 짝이 잡힌 행도 지운다 — 화면을 떠난 사람의 자리를 남겨 두면 상대가
// 아무도 안 오는 방에서 기다린다.
func (q *Queries) LeaveQueue(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, leaveQueue, userID)
	return err
}

const lockQueueCandidates = `-- name: LockQueueCandidates :many
SELECT q.user_id, q.rating, q.deviation, q.joined_at, u.display_name
FROM match_queue q
         JOIN users u ON u.id = q.user_id
WHERE q.room_id IS NULL AND q.user_id <> $1 AND q.seen_at >= $2
  AND q.rating BETWEEN $3 AND $4
ORDER BY q.joined_at
LIMIT $5
FOR UPDATE OF q SKIP LOCKED
`

type LockQueueCandidatesParams struct {
	UserID   int64
	SeenAt   pgtype.Timestamptz
	Rating   float64
	Rating_2 float64
	Limit    int32
}

type LockQueueCandidatesRow struct {
	UserID      int64
	Rating      float64
	Deviation   float64
	JoinedAt    pgtype.Timestamptz
	DisplayName string
}

// 후보를 오래 기다린 순으로 잠근다. 고르는 것은 부르는 쪽이다(internal/queue.Pick).
//
// SKIP LOCKED 가 「두 인스턴스가 같은 대기자를 두 번 집지 않는다」를 맡는다
// (ClaimGameForResume 과 같은 계열). 모든 잠금이 SKIP LOCKED 라 아무도 기다리지 않고,
// 그래서 서로를 집는 두 짝짓기가 교착에 빠질 자리가 없다.
//
// 낡은 행은 후보가 아니다($2). 위 SweepQueue 가 지우기 전에도 그 사람은 이미 화면을
// 떠났고, 그 사람과 짝을 지으면 상대가 아무도 안 오는 방에서 60초를 기다린다.
//
// 레이팅으로 미리 자른다($3·$4). 밴드가 아니라 그 상한이고(queue.MaxBand) 두 가지를 한다.
// 잠기는 행이 「붙을 가능성이 있는 사람」으로 줄어서 남의 짝짓기가 헛돌지 않고, 후보
// 앞머리가 밴드 밖으로 채워지지 않는다 — 안 자르면 대기열이 길 때 앞머리 20줄이 전부 밴드
// 밖일 수 있고, 그때 짝이 있는데도 안 잡힌다.
//
// 이 폭은 어떤 밴드보다 넓다. 좁게 자르면 붙을 수 있는 짝을 잠그기 전에 버린다.
//
// 이름을 같이 든다. 짝을 지으면 그 자리에서 방을 세워야 하고(match.Hub.CreatePaired) 방은
// 두 사람의 표시 이름을 든다 — 따로 읽으면 그 사이에 사람이 사라진 경우가 하나 더 생긴다.
//
// 잠그는 것은 대기열 행이다(OF q). users 를 같이 잠그면 로그인 하나가 짝짓기를 기다린다.
func (q *Queries) LockQueueCandidates(ctx context.Context, arg LockQueueCandidatesParams) ([]LockQueueCandidatesRow, error) {
	rows, err := q.db.Query(ctx, lockQueueCandidates,
		arg.UserID,
		arg.SeenAt,
		arg.Rating,
		arg.Rating_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockQueueCandidatesRow
	for rows.Next() {
		var i LockQueueCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Rating,
			&i.Deviation,
			&i.JoinedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockQueueWaiter = `-- name: LockQueueWaiter :one
SELECT user_id, rating, deviation, joined_at
FROM match_queue
WHERE user_id = $1 AND room_id IS NULL
FOR UPDATE SKIP LOCKED
`

type LockQueueWaiterRow struct {
	UserID    int64
	Rating    float64
	Deviation float64
	JoinedAt  pgtype.Timestamptz
}

// 내 행을 잠근다. 없거나 남이 잠그고 있으면 0행이다.
//
// SKIP LOCKED 라서 기다리지 않는다. 그 사이 남이 나를 짝으로 집고 있는 것이고, 그때는
// 짝짓기를 포기하는 것이 맞다 — 다음 재시도에서 내 행에 방 id 가 적혀 있다.
//
// 이것도 잠그는 이유는 두 짝짓기가 서로를 동시에 집는 자리다. 내 행을 안 잠그면
// A가 B를, B가 A를 집어 방이 둘 생기고 네 자리에 두 사람이 앉는다.
func (q *Queries) LockQueueWaiter(ctx context.Context, userID int64) (LockQueueWaiterRow, error) {
	row := q.db.QueryRow(ctx, lockQueueWaiter, userID)
	var i LockQueueWaiterRow
	err := row.Scan(
		&i.UserID,
		&i.Rating,
		&i.Deviation,
		&i.JoinedAt,
	)
	return i, err
}

const seatQueueWaiter = `-- name: SeatQueueWaiter :execrows
UPDATE match_queue
SET room_id = $2, color = $3, matched_at = now()
WHERE user_id = $1 AND room_id IS NULL
`

type SeatQueueWaiterParams struct {
	UserID int64
	RoomID *string
	Color  *string
}

// 짝의 행에 방 쪽지를 적는다. 이미 잠가 둔 행이라(LockQueueCandidates) 여기서 조건이
// 어긋날 자리는 없지만, room_id IS NULL 을 남겨 두는 것은 이 문장 하나만 봐도
// 「안 잡힌 행에만 적는다」가 읽히게 하기 위해서다.
func (q *Queries) SeatQueueWaiter(ctx context.Context, arg SeatQueueWaiterParams) (int64, error) {
	result, err := q.db.Exec(ctx, seatQueueWaiter, arg.UserID, arg.RoomID, arg.Color)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepQueue = `-- name: SweepQueue :exec
DELETE FROM match_queue
WHERE (room_id IS NULL AND seen_at < $1)
   OR (room_id IS NOT NULL AND matched_at < $2)
`

type SweepQueueParams struct {
	SeenAt    pgtype.Timestamptz
	MatchedAt pgtype.Timestamptz
}

// 낡은 행을 걷는다. 대기열에 서는 그 요청이 부른다 — 리더도 sweeper 도 두지 않는 것이
// 이 대기열의 설계다(journal §92).
//
// 두 가지를 한 문장에서 건다. 다시 안 물어보는 대기자($1 보다 오래된 seen_at)와,
// 짝이 잡혔는데 안 찾아간 자리($2 보다 오래된 matched_at)다.
func (q *Queries) SweepQueue(ctx context.Context, arg SweepQueueParams) error {
	_, err := q.db.Exec(ctx, sweepQueue, arg.SeenAt, arg.MatchedAt)
	return err
}

const takeQueueSeat = `-- name: TakeQueueSeat :one
DELETE FROM match_queue
WHERE user_id = $1 AND room_id IS NOT NULL
RETURNING room_id, color
`

type TakeQueueSeatRow struct {
	RoomID *string
	Color  *string
}

// 짝이 잡혔으면 그 자리를 주고 행을 지운다. 아직이면 0행이다.
//
// 읽는 것과 지우는 것이 한 문장이다. 갈라 두면 그 사이에 다시 물어본 요청이 같은 자리를
// 두 번 받고, 화면이 두 번 방으로 간다 — 방은 정원이 둘이라 두 번째가 남의 자리를 노린다.
func (q *Queries) TakeQueueSeat(ctx context.Context, userID int64) (TakeQueueSeatRow, error) {
	row := q.db.QueryRow(ctx, takeQueueSeat, userID)
	var i TakeQueueSeatRow
	err := row.Scan(&i.RoomID, &i.Color)
	return i, err
}
