// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz.sql

package db

import (
	"context"
)

const getGameQuiz = `-- name: GetGameQuiz :one

SELECT version, payload FROM game_quizzes WHERE game_id = $1
`

type GetGameQuizRow struct {
	Version int32
	Payload []byte
}

// 되짚기 퀴즈. 한 판에 한 행이고 늘 통째로 읽고 쓴다(migrations/007).
func (q *Queries) GetGameQuiz(ctx context.Context, gameID int64) (GetGameQuizRow, error) {
	row := q.db.QueryRow(ctx, getGameQuiz, gameID)
	var i GetGameQuizRow
	err := row.Scan(&i.Version, &i.Payload)
	return i, err
}

const upsertGameQuiz = `-- name: UpsertGameQuiz :exec
INSERT INTO game_quizzes (game_id, version, payload)
VALUES ($1, $2, $3)
ON CONFLICT (game_id) DO UPDATE
SET version = EXCLUDED.version, payload = EXCLUDED.payload, generated_at = now()
`

type UpsertGameQuizParams struct {
	GameID  int64
	Version int32
	Payload []byte
}

// 덮어쓰는 조건을 안 건다. `positions` 와 다른 점이고(저쪽은 얕은 결과가 깊은 것을 덮지
// 못하게 막는다), 이쪽은 **한 판에 생성이 한 번**이라 경합할 상대가 없다. 다시 만드는
// 자리가 생기면 그때 새 결과가 정본이다.
func (q *Queries) UpsertGameQuiz(ctx context.Context, arg UpsertGameQuizParams) error {
	_, err := q.db.Exec(ctx, upsertGameQuiz, arg.GameID, arg.Version, arg.Payload)
	return err
}
