// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rating.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRating = `-- name: GetRating :one

SELECT rating_est, rating_sd, rating_games, rating_updated_at, skill_loss, skill_samples
FROM skill_profile
WHERE user_id = $1
`

type GetRatingRow struct {
	RatingEst       float64
	RatingSd        float64
	RatingGames     int32
	RatingUpdatedAt pgtype.Timestamptz
	SkillLoss       *float64
	SkillSamples    int32
}

// 매칭 레이팅. 근거는 journal §92.
//
// 밖으로 안 나간다. 어느 API 도 이 값을 돌려주지 않으므로 소유자 조건이 없다 —
// 부르는 쪽이 대국 기록에서 얻은 두 user_id 로만 부른다(server/match_records.go).
//
// 없으면 0행이다. rating_games = 0 이면 행은 있어도 레이팅이 없는 것이고, 그 둘을
// 부르는 쪽이 같게 다룬다 — 엔진 대국만 한 사람은 skill_loss 때문에 행이 이미 있다.
func (q *Queries) GetRating(ctx context.Context, userID int64) (GetRatingRow, error) {
	row := q.db.QueryRow(ctx, getRating, userID)
	var i GetRatingRow
	err := row.Scan(
		&i.RatingEst,
		&i.RatingSd,
		&i.RatingGames,
		&i.RatingUpdatedAt,
		&i.SkillLoss,
		&i.SkillSamples,
	)
	return i, err
}

const saveMatchRatings = `-- name: SaveMatchRatings :exec
INSERT INTO skill_profile (user_id, rating_est, rating_sd, rating_games, rating_updated_at)
VALUES ($1, $2, $3, 1, now()),
       ($4, $5, $6, 1, now())
ON CONFLICT (user_id) DO UPDATE
SET rating_est        = EXCLUDED.rating_est,
    rating_sd         = EXCLUDED.rating_sd,
    -- 넘겨받은 값이 아니라 지금 값에 더한다. 부르는 쪽이 읽은 뒤로 다른 판이 끝났으면
    -- 그 판까지 세어야 하고, 세는 것이 이 칸의 유일한 일이다.
    rating_games      = skill_profile.rating_games + 1,
    rating_updated_at = now()
`

type SaveMatchRatingsParams struct {
	UserID      int64
	RatingEst   float64
	RatingSd    float64
	UserID_2    int64
	RatingEst_2 float64
	RatingSd_2  float64
}

// 한 문장으로 두 사람을 같이 옮긴다. 트랜잭션을 안 여는 이유는 여기가 원자적이면
// 열 것이 없기 때문이다 — 반쪽만 반영된 판이 남으면 그 뒤로 두 사람의 레이팅이
// 서로 다른 판 수 위에서 돈다.
//
// 같은 user_id 를 두 번 넘기면 Postgres 가 거절한다(ON CONFLICT 가 한 행을 두 번 못
// 고친다). 한 판의 두 사람은 언제나 다르므로 그 자리는 안 온다(match.Hub.Enter).
func (q *Queries) SaveMatchRatings(ctx context.Context, arg SaveMatchRatingsParams) error {
	_, err := q.db.Exec(ctx, saveMatchRatings,
		arg.UserID,
		arg.RatingEst,
		arg.RatingSd,
		arg.UserID_2,
		arg.RatingEst_2,
		arg.RatingSd_2,
	)
	return err
}
