// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill.sql

package db

import (
	"context"
)

const getSkillProfile = `-- name: GetSkillProfile :one

SELECT skill_loss, skill_samples
FROM skill_profile
WHERE user_id = $1
`

type GetSkillProfileRow struct {
	SkillLoss    *float64
	SkillSamples int32
}

// 실력 프로파일. 본인만 조회할 수 있어야 한다(02-architecture.md §7 위협 2) —
// 여기 오는 user_id 는 언제나 서명 쿠키에서 나온 값이다(server/auth.go).
//
// 없으면 0행이다. 부르는 쪽이 그때 「아직 모른다」로 시작한다 — 행을 미리 만들지 않는 것은
// 로그인만 하고 안 두는 사람에게 빈 행을 남기지 않기 위해서다.
func (q *Queries) GetSkillProfile(ctx context.Context, userID int64) (GetSkillProfileRow, error) {
	row := q.db.QueryRow(ctx, getSkillProfile, userID)
	var i GetSkillProfileRow
	err := row.Scan(&i.SkillLoss, &i.SkillSamples)
	return i, err
}

const saveSkillEstimate = `-- name: SaveSkillEstimate :exec
INSERT INTO skill_profile (user_id, skill_loss, skill_samples)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET skill_loss    = EXCLUDED.skill_loss,
    skill_samples = EXCLUDED.skill_samples,
    updated_at    = now()
`

type SaveSkillEstimateParams struct {
	UserID       int64
	SkillLoss    *float64
	SkillSamples int32
}

// 판정 한 건마다 부른다. 대국이 끝날 때 한 번이 아니다 — 새로고침하면 판이 끝나므로
// (journal §46) 끝에 몰아 쓰면 중간에 끊긴 판의 추정이 통째로 사라진다.
//
// weakness 는 건드리지 않는다. 카테고리별 발생률은 아직 쓰는 쪽이 없다.
func (q *Queries) SaveSkillEstimate(ctx context.Context, arg SaveSkillEstimateParams) error {
	_, err := q.db.Exec(ctx, saveSkillEstimate, arg.UserID, arg.SkillLoss, arg.SkillSamples)
	return err
}
