// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timings.sql

package db

import (
	"context"
)

const insertSearchTiming = `-- name: InsertSearchTiming :exec

INSERT INTO search_timings (sfen_key, depth, k, ms, cached)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSearchTimingParams struct {
	SFENKey string
	Depth   int32
	K       int32
	Ms      int32
	Cached  bool
}

// 탐색 하나의 소요 시간. depth·k 별 비용을 나중에 보기 위한 기록이다.
// 서버는 쓰기만 하고 읽는 쪽은 사람이다(DB 클라이언트).
func (q *Queries) InsertSearchTiming(ctx context.Context, arg InsertSearchTimingParams) error {
	_, err := q.db.Exec(ctx, insertSearchTiming,
		arg.SFENKey,
		arg.Depth,
		arg.K,
		arg.Ms,
		arg.Cached,
	)
	return err
}
