// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (provider, provider_uid, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_uid) DO UPDATE
SET display_name = EXCLUDED.display_name
RETURNING id
`

type UpsertUserParams struct {
	Provider    string
	ProviderUid string
	DisplayName string
}

// 로그인한 사람. provider 는 지금 'google' 하나다.
//
// **provider_uid 로 찾는다.** 이메일이 아니다 — 이메일은 바뀌고, 지운 계정의 것이
// 다른 사람에게 다시 나갈 수 있다. Google의 `sub` 는 그 계정에 붙어 안 바뀐다.
//
// 이름은 로그인할 때마다 덮는다. 저쪽에서 바꾼 이름이 다음 로그인에 따라온다.
// 충돌해도 RETURNING 이 오도록 DO UPDATE 다 — DO NOTHING 이면 이미 있는 사람의
// 로그인이 0행을 받는다.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Provider, arg.ProviderUid, arg.DisplayName)
	var id int64
	err := row.Scan(&id)
	return id, err
}
